import enum

from machineq.core.shared.models import BaseModelWithConfig


class PayloadDecoderType(str, enum.Enum):
    UNKNOWN = "UNKNOWN"
    MOTE = "MOTE"
    ELSYS = "ELSYS"
    NETVOX = "NETVOX"
    LPP = "LPP"
    GLOBALSAT = "GLOBALSAT"
    LPP_CHANNELS = "LPP_CHANNELS"
    H2O = "H2O"
    MQPS = "MQPS"
    LAIIER_SEVERN_WLD = "LAIIER_SEVERN_WLD"
    MOKOSMART_MK_117 = "MOKOSMART_MK_117"
    MILESIGHT_VS_133 = "MILESIGHT_VS_133"
    MILESIGHT_VS_330 = "MILESIGHT_VS_330"
    MILESIGHT_WS_101 = "MILESIGHT_WS_101"
    MILESIGHT_WS_201 = "MILESIGHT_WS_201"
    MILESIGHT_EM_300_CL = "MILESIGHT_EM_300_CL"
    GEORGIA_PACIFIC_KOLO_2_0 = "GEORGIA_PACIFIC_KOLO_2_0"
    MILESIGHT_EM_310_UDL = "MILESIGHT_EM_310_UDL"
    VUTILITY_HOTDROP_DIRECT = "VUTILITY_HOTDROP_DIRECT"
    MOKOSMART_LW009_SM = "MOKOSMART_LW009_SM"
    MILESIGHT_EM_500_PT100 = "MILESIGHT_EM_500_PT100"
    MILESIGHT_DS3604 = "MILESIGHT_DS3604"
    VICTOR_VLINK_V4XX = "VICTOR_VLINK_V4XX"
    MILESIGHT_VS350 = "MILESIGHT_VS350"
    MILESIGHT_EM320_TH = "MILESIGHT_EM320_TH"
    MILESIGHT_AM308_V2 = "MILESIGHT_AM308_V2"
    MILESIGHT_EM400_TLD = "MILESIGHT_EM400_TLD"
    MILESIGHT_EM400_MUD = "MILESIGHT_EM400_MUD"
    MILESIGHT_EM500_PP = "MILESIGHT_EM500_PP"
    MACHINEQ_MQPS_V2 = "MACHINEQ_MQPS_V2"
    MILESIGHT_VS341 = "MILESIGHT_VS341"
    MILESIGHT_CT101 = "MILESIGHT_CT101"
    MILESIGHT_CT103 = "MILESIGHT_CT103"
    MILESIGHT_CT303 = "MILESIGHT_CT303"
    MILESIGHT_WTS506 = "MILESIGHT_WTS506"
    MILESIGHT_UC300 = "MILESIGHT_UC300"
    GEORGIA_PACIFIC_KOLO_CLICK_SPINDLE = "GEORGIA_PACIFIC_KOLO_CLICK_SPINDLE"
    GEORGIA_PACIFIC_KOLO_CLICK_8AND10_TOWEL = "GEORGIA_PACIFIC_KOLO_CLICK_8AND10_TOWEL"


class DecoderTypeInstance(BaseModelWithConfig):
    id: str
    name: str
    payload_decoder: PayloadDecoderType


class DecoderTypeCreateResponse(BaseModelWithConfig):
    id: str


class DecoderTypeError(BaseModelWithConfig):
    response: bool


class DecoderTypeResponse(BaseModelWithConfig):
    decoder_types: list[DecoderTypeInstance]
